import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { AppNav } from "~/components/AppNav";
import { FlowConnectionProvider } from "~/components/FlowConnectionProvider";
import { ToastProvider } from "~/components/ui/use-toast";
import { Toaster } from "~/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
  },
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ToastProvider>
          <FlowConnectionProvider>
            <AppNav />
            {children}
          </FlowConnectionProvider>
          <Toaster />
        </ToastProvider>
      </body>
    </html>
  );
}
