CREATE TABLE "elizbeth_central_command_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "elizbeth_central_command_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_brew_ledger_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elizbeth_central_command_brew_ledger_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"coffeeId" integer NOT NULL,
	"recipeId" integer,
	"brewedAt" timestamp with time zone NOT NULL,
	"brewMethod" varchar(64) NOT NULL,
	"doseGrams" double precision,
	"yieldGrams" double precision,
	"brewRatio" double precision,
	"grindSetting" varchar(128),
	"waterTempC" double precision,
	"brewTimeSeconds" integer,
	"profileRef" varchar(128),
	"profileNameSnapshot" varchar(256),
	"grinder" varchar(128),
	"rating" integer,
	"waterRecipe" varchar(256),
	"tastingNotes" text,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_coffee_recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elizbeth_central_command_coffee_recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"coffeeId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"brewMethod" varchar(64) NOT NULL,
	"doseGrams" double precision,
	"yieldGrams" double precision,
	"brewRatio" double precision,
	"grindSetting" varchar(128),
	"waterTempC" double precision,
	"brewTimeSeconds" integer,
	"profileRef" varchar(128),
	"profileNameSnapshot" varchar(256),
	"tastingNotes" text,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_coffee" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elizbeth_central_command_coffee_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"roaster" varchar(256),
	"origin" varchar(256),
	"process" varchar(128),
	"roastLevel" varchar(64),
	"roastDate" timestamp with time zone,
	"purchaseDate" timestamp with time zone,
	"notes" text,
	"tastingNotes" text,
	"preferredProfileRef" varchar(128),
	"preferredProfileName" varchar(256),
	"defaultBrewMethod" varchar(64),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elizbeth_central_command_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "elizbeth_central_command_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "elizbeth_central_command_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_account" ADD CONSTRAINT "elizbeth_central_command_account_userId_elizbeth_central_command_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."elizbeth_central_command_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_brew_ledger_entry" ADD CONSTRAINT "elizbeth_central_command_brew_ledger_entry_coffeeId_elizbeth_central_command_coffee_id_fk" FOREIGN KEY ("coffeeId") REFERENCES "public"."elizbeth_central_command_coffee"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_brew_ledger_entry" ADD CONSTRAINT "elizbeth_central_command_brew_ledger_entry_recipeId_elizbeth_central_command_coffee_recipe_id_fk" FOREIGN KEY ("recipeId") REFERENCES "public"."elizbeth_central_command_coffee_recipe"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_coffee_recipe" ADD CONSTRAINT "elizbeth_central_command_coffee_recipe_coffeeId_elizbeth_central_command_coffee_id_fk" FOREIGN KEY ("coffeeId") REFERENCES "public"."elizbeth_central_command_coffee"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_post" ADD CONSTRAINT "elizbeth_central_command_post_createdById_elizbeth_central_command_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."elizbeth_central_command_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_session" ADD CONSTRAINT "elizbeth_central_command_session_userId_elizbeth_central_command_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."elizbeth_central_command_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "elizbeth_central_command_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "brew_ledger_coffee_id_idx" ON "elizbeth_central_command_brew_ledger_entry" USING btree ("coffeeId");--> statement-breakpoint
CREATE INDEX "brew_ledger_recipe_id_idx" ON "elizbeth_central_command_brew_ledger_entry" USING btree ("recipeId");--> statement-breakpoint
CREATE INDEX "brew_ledger_brewed_at_idx" ON "elizbeth_central_command_brew_ledger_entry" USING btree ("brewedAt");--> statement-breakpoint
CREATE INDEX "coffee_recipe_coffee_id_idx" ON "elizbeth_central_command_coffee_recipe" USING btree ("coffeeId");--> statement-breakpoint
CREATE INDEX "coffee_recipe_created_at_idx" ON "elizbeth_central_command_coffee_recipe" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "coffee_name_idx" ON "elizbeth_central_command_coffee" USING btree ("name");--> statement-breakpoint
CREATE INDEX "coffee_created_at_idx" ON "elizbeth_central_command_coffee" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "elizbeth_central_command_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "elizbeth_central_command_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "elizbeth_central_command_session" USING btree ("userId");