CREATE TABLE "elizbeth_central_command_coffee_bag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elizbeth_central_command_coffee_bag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"coffeeId" integer NOT NULL,
	"openedAt" timestamp with time zone NOT NULL,
	"finishedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "elizbeth_central_command_coffee_bag" ADD CONSTRAINT "elizbeth_central_command_coffee_bag_coffeeId_elizbeth_central_command_coffee_id_fk" FOREIGN KEY ("coffeeId") REFERENCES "public"."elizbeth_central_command_coffee"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "coffee_bag_coffee_id_idx" ON "elizbeth_central_command_coffee_bag" USING btree ("coffeeId");--> statement-breakpoint
CREATE INDEX "coffee_bag_opened_at_idx" ON "elizbeth_central_command_coffee_bag" USING btree ("openedAt");--> statement-breakpoint
CREATE INDEX "coffee_bag_finished_at_idx" ON "elizbeth_central_command_coffee_bag" USING btree ("finishedAt");--> statement-breakpoint
INSERT INTO "elizbeth_central_command_coffee_bag" ("coffeeId", "openedAt", "finishedAt", "createdAt", "updatedAt")
SELECT
  "id",
  COALESCE("purchaseDate", "createdAt"),
  NULL,
  COALESCE("purchaseDate", "createdAt"),
  NULL
FROM "elizbeth_central_command_coffee"
WHERE NOT EXISTS (
  SELECT 1
  FROM "elizbeth_central_command_coffee_bag" AS bag
  WHERE bag."coffeeId" = "elizbeth_central_command_coffee"."id"
);